CREATE SCHEMA EDUCATION;



USE EDUCATION;
CREATE TABLE enrollment2018 
(ENTITY_CD INTEGER PRIMARY KEY,
ENTITY_NAME  VARCHAR(260),
School_Year INTEGER,
PK INTEGER,
PKHALF INTEGER,
PKFULL INTEGER,
KHALF INTEGER,
KFULL INTEGER,
Grade_1 INTEGER,
Grade_2 INTEGER,
Grade_3 INTEGER,
Grade_4 INTEGER,
Grade_5 INTEGER,
Grade_6 INTEGER,
Grade_7 INTEGER,
Grade_8 INTEGER,
Grade_9 INTEGER,
Grade_10 INTEGER,
Grade_11 INTEGER,
Grade_12 INTEGER,
UGE INTEGER,
UGS INTEGER,
K12 INTEGER
);

SELECT * FROM enrollment2018